//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_UPLOAD
    {
        public string ID { get; set; }
        public string FK_USERID { get; set; }
        public string UPOPEATOR { get; set; }
        public Nullable<System.DateTime> UPTIME { get; set; }
        public string UPOLDNAME { get; set; }
        public string UPNEWNAME { get; set; }
        public Nullable<decimal> UPFILESIZE { get; set; }
        public string UPFILEUNIT { get; set; }
        public string UPFILEPATH { get; set; }
        public string UPFILESUFFIX { get; set; }
        public string UPFILETHUMBNAIL { get; set; }
        public string UPFILETHUMBNAILFORPAD { get; set; }
        public string UPFILETHUMBNAILFORPHONE { get; set; }
        public string UPFILEIP { get; set; }
        public string UPFILEURL { get; set; }
    }
}
