//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_WORKATTENDANCE
    {
        public int ID { get; set; }
        public int FK_UserId { get; set; }
        public bool Is_SiginAM { get; set; }
        public bool Is_SigOutAM { get; set; }
        public System.DateTime SiginAMDate { get; set; }
        public System.DateTime SigOutAMDate { get; set; }
        public bool Is_SiginPM { get; set; }
        public bool Is_SigOutPM { get; set; }
        public System.DateTime SiginPM { get; set; }
        public System.DateTime SigOutPM { get; set; }
        public bool IsLateAM { get; set; }
        public int LateAMMinutes { get; set; }
        public bool IsEarlyOutAM { get; set; }
        public int EarlyOutAMMinutes { get; set; }
        public bool IsLatePM { get; set; }
        public int LatePMMinutes { get; set; }
        public bool IsEarlyOutPM { get; set; }
        public int EarlyOutPMMinutes { get; set; }
        public double WorkHours { get; set; }
        public string SigIP { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
