//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_ATTACHMENT
    {
        public int ID { get; set; }
        public int FK_MailID { get; set; }
        public string AttName { get; set; }
        public string AttNewName { get; set; }
        public string AttPath { get; set; }
        public string AttExt { get; set; }
        public string AttSize { get; set; }
        public string CreateIP { get; set; }
        public System.DateTime UploadDate { get; set; }
    
        public virtual MAIL_OUTBOX MAIL_OUTBOX { get; set; }
    }
}
