//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_PROJECTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRO_PROJECTS()
        {
            this.PRO_PROJECT_MESSAGE = new HashSet<PRO_PROJECT_MESSAGE>();
            this.PRO_PROJECT_STAGES = new HashSet<PRO_PROJECT_STAGES>();
        }
    
        public int ID { get; set; }
        public string ProjectTitle { get; set; }
        public string FK_RELATIONID { get; set; }
        public string Fk_DepartId { get; set; }
        public int Fk_UserId { get; set; }
        public int ProjectStatus { get; set; }
        public int Fk_BussinessCustomer { get; set; }
        public int ProjectLevels { get; set; }
        public decimal ProjectMoney { get; set; }
        public int ProjectTimeLimit { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string ContractCode { get; set; }
        public string ContractFile { get; set; }
        public string SignPersion { get; set; }
        public System.DateTime SignDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_PROJECT_MESSAGE> PRO_PROJECT_MESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_PROJECT_STAGES> PRO_PROJECT_STAGES { get; set; }
    }
}
