//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_PROJECT_MESSAGE
    {
        public int ID { get; set; }
        public int FK_ProjectId { get; set; }
        public string MessageContent { get; set; }
        public string UserName { get; set; }
        public string UserFace { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual PRO_PROJECTS PRO_PROJECTS { get; set; }
    }
}
