//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_PROJECT_FILES
    {
        public int ID { get; set; }
        public string DocStyle { get; set; }
        public int Fk_ForeignId { get; set; }
        public int FK_UserId { get; set; }
        public string DocName { get; set; }
        public string DocNewName { get; set; }
        public string DocPath { get; set; }
        public string DocFileExt { get; set; }
        public string DocSize { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string CreateUser { get; set; }
        public string CreateIP { get; set; }
        public Nullable<int> AcceptanceStatus { get; set; }
    }
}
