//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_PROJECT_TEAMS
    {
        public int ID { get; set; }
        public int FK_StageId { get; set; }
        public int FK_UserId { get; set; }
        public string ApplyReasons { get; set; }
        public int JionStatus { get; set; }
        public string RefuseReasons { get; set; }
        public System.DateTime JionDate { get; set; }
    
        public virtual PRO_PROJECT_STAGES PRO_PROJECT_STAGES { get; set; }
    }
}
