//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PERMISSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_PERMISSION()
        {
            this.SYS_ROLE_PERMISSION = new HashSet<SYS_ROLE_PERMISSION>();
            this.SYS_USER_PERMISSION = new HashSet<SYS_USER_PERMISSION>();
        }
    
        public int ID { get; set; }
        public int MODULEID { get; set; }
        public string NAME { get; set; }
        public string PERVALUE { get; set; }
        public string ICON { get; set; }
        public Nullable<int> SHOWORDER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEUSER { get; set; }
    
        public virtual SYS_MODULE SYS_MODULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_ROLE_PERMISSION> SYS_ROLE_PERMISSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_USER_PERMISSION> SYS_USER_PERMISSION { get; set; }
    }
}
