//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CODE
    {
        public int ID { get; set; }
        public string CODETYPE { get; set; }
        public string NAMETEXT { get; set; }
        public string CODEVALUE { get; set; }
        public Nullable<int> SHOWORDER { get; set; }
        public bool ISCODE { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<int> PARENTID { get; set; }
    }
}
