//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_DEPARTMENT()
        {
            this.SYS_POST = new HashSet<SYS_POST>();
        }
    
        public string ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<int> BUSINESSLEVEL { get; set; }
        public Nullable<int> SHOWORDER { get; set; }
        public string CREATEPERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string PARENTID { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEUSER { get; set; }
        public string PARENTCODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_POST> SYS_POST { get; set; }
    }
}
