//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SYSTEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_SYSTEM()
        {
            this.SYS_MODULE = new HashSet<SYS_MODULE>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string SITEURL { get; set; }
        public bool IS_LOGIN { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string REMARK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_MODULE> SYS_MODULE { get; set; }
    }
}
