//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER_ONLINE
    {
        public int ID { get; set; }
        public string ConnectId { get; set; }
        public int FK_UserId { get; set; }
        public System.DateTime OnlineDate { get; set; }
        public Nullable<System.DateTime> OfflineDate { get; set; }
        public bool IsOnline { get; set; }
        public string UserIP { get; set; }
    
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
