//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USERINFO
    {
        public int ID { get; set; }
        public int USERID { get; set; }
        public Nullable<int> POSTCODE { get; set; }
        public string PHONE { get; set; }
        public string OFFICEPHONE { get; set; }
        public string EMAILADDRESS { get; set; }
        public string SECONDPHONE { get; set; }
        public Nullable<int> WORKCODE { get; set; }
        public Nullable<int> SEXCODE { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<int> NATIONCODE { get; set; }
        public string IDNUMBER { get; set; }
        public Nullable<int> MARRYCODE { get; set; }
        public Nullable<int> IDENTITYCODE { get; set; }
        public string HomeTown { get; set; }
        public string ACCOUNTLOCATION { get; set; }
        public Nullable<int> XUELI { get; set; }
        public Nullable<int> ZHICHENG { get; set; }
        public string GRADUATIONSCHOOL { get; set; }
        public string SPECIALTY { get; set; }
        public string PHOTOOLDNAME { get; set; }
        public string PHOTONEWNAME { get; set; }
        public string PHOTOTYPE { get; set; }
        public string RESUMEOLDNAME { get; set; }
        public string RESUMENEWNAME { get; set; }
        public string RESUMETYPE { get; set; }
        public string HuJiSuoZaiDi { get; set; }
        public string HUJIPAICHUSUO { get; set; }
        public Nullable<System.DateTime> WORKDATE { get; set; }
        public Nullable<System.DateTime> JINRUDATE { get; set; }
        public string CARNUMBER { get; set; }
        public string QQ { get; set; }
        public string WEBCHATOPENID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEUSER { get; set; }
    
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
