//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_POST
    {
        public string ID { get; set; }
        public string FK_DEPARTID { get; set; }
        public string POSTNAME { get; set; }
        public string POSTTYPE { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> SHOWORDER { get; set; }
        public string CREATEUSER { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEUSER { get; set; }
    
        public virtual SYS_DEPARTMENT SYS_DEPARTMENT { get; set; }
    }
}
